# MM algoritm

In [17]:
# Binary logistic regression using MM algorithm

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm, binom
import time

In [18]:
# Generate data
np.random.seed(1)
n = 10000
p = 5
X = np.random.normal(size=(n, p))
beta = np.random.normal(size=p)
y = np.random.binomial(1, norm.cdf(X @ beta))

In [34]:
# MM algorithm for binary logistic regression
def MM(X, y, max_iter=1000, tol=1e-6):
    start_time = time.time()
    n, p = X.shape
    beta = np.zeros(p)
    Hessian = 4 * np.linalg.inv(X.T @ X)

    for i in range(max_iter):
        eta = X @ beta
        mu = np.exp(eta) / (1 + np.exp(eta))
        gradient = X.T @ (y - mu)
        beta_new = beta + Hessian @ gradient

        if np.linalg.norm(beta_new - beta) < tol:
            break
        beta = beta_new

    return beta, time.time() - start_time

beta_hat_MM, time_MM = MM(X, y)

In [36]:
beta

array([-0.89388483, -0.37188981,  0.19532995, -1.25642386, -0.18809661])

In [35]:
beta_hat_MM

array([-1.51561681, -0.66973556,  0.34973809, -2.14170206, -0.28465471])

In [38]:
# Compare with iterative reweighted least squares
def IRLS(X, y, max_iter=1000, tol=1e-6):
    start_time = time.time()
    n, p = X.shape
    beta = np.zeros(p)

    for i in range(max_iter):
        eta = X @ beta
        mu = np.exp(eta) / (1 + np.exp(eta))
        W = np.diag(mu * (1 - mu))
        Hessian = X.T @ W @ X
        gradient = X.T @ (y - mu)
        beta_new = beta + np.linalg.inv(Hessian) @ gradient
        if np.linalg.norm(beta_new - beta) < tol:
            end_time = time.time()
            break
        beta = beta_new
    return beta, end_time - start_time

beta_hat_IRLS, time_IRLS = IRLS(X, y)

In [39]:
beta_hat_IRLS

array([-1.51562053, -0.66973723,  0.34973898, -2.1417074 , -0.28465542])

In [40]:
print('MM algorithm: ', time_MM)
print('IRLS: ', time_IRLS)

MM algorithm:  0.17301678657531738
IRLS:  1.429758071899414
